### PR TITLE
Override hostname to match EC2's PrivateDnsName

### LINKED ISSUE #1263: 1.26 nodes fail to join the cluster with custom VPC domain-name
**What happened**:
1.26 AMI Nodes fail to join 1.26 clusters. In both scenarios of upgrading from 1.25 to 1.26 and new clusters starting fresh with 1.26

**What you expected to happen**:
The nodes to join the cluster

**Anything else we need to know?**:
* Using manged node groups.
* The exact same Terraform deployment configuration works on 1.25. The only thing changed is the version for cluster/ami which triggers the failure on both upgrades and new clusters.
* VPC DHCP domain name is in the format: `ec2.internal acmedev.com`

**Environment**:
- AWS Region: `us-east-1`
- Instance Type(s): `m6a`
- EKS Platform version: `"eks.1"`
- Kubernetes version: `"1.26"`
- AMI Version: `amazon-eks-node-1.26-v20230406`
- Kernel (e.g. `uname -a`): `Linux ip-10-100-13-0.ec2.internalacmedev.com 5.10.173-154.642.amzn2.x86_64 #1 SMP Wed Mar 15 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node): 

```
BASE_AMI_ID="ami-099e00fe4091e48af"
BUILD_TIME="Thu Apr  6 01:36:39 UTC 2023"
BUILD_KERNEL="5.10.173-154.642.amzn2.x86_64"
ARCH="x86_64"
```
I believe the change in `cloud-provider` from `aws` to `external` has created an issue where our hostname for the kubelet is different between 1.25 and 1.26. This causes the aws iam authenticator node bootstrap logic to fail to register with the cluster because the hostname in the requests are not the same.

hostnamed logs are the exact same on 1.25 and 1.26 nodes, including the "warning"
```
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed pretty host name to 'ip-10-100-13-0.ec2.internal acmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed static host name to 'ip-10-100-13-0.ec2.internalacmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed host name to 'ip-10-100-13-0.ec2.internalacmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 cloud-init: Apr 13 13:55:48 cloud-init[2209]: util.py[WARNING]: Failed to non-persistently adjust the system hostname to ip-10-100-13-0.ec2.internal acmedev.com
```

We are not changing any of the kubelet arguments from their AMI defaults. The only thing we are doing is adding some labels/taints to the nodes via the managed node group terraform resources. No hostname overrides.
```
Apr 13 13:55:53 ip-10-100-13-0 kubelet: I0413 13:55:53.946396    2944 flags.go:64] FLAG: --cloud-provider="external"
Apr 13 13:55:53 ip-10-100-13-0 kubelet: I0413 13:55:53.946638    2944 flags.go:64] FLAG: --hostname-override=""
```

Pertinent messages that indicate node join failures.
```Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.191968    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasSufficientMemory"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.192348    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasNoDiskPressure"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.192745    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasSufficientPID"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.193204    2944 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.765164    2944 controller.go:146] failed to ensure lease exists, will retry in 200ms, error: leases.coordination.k8s.io "ip-10-100-13-0.ec2.internalacmedev.com" is forbidden: User "system:node:ip-10-100-13-0.ec2.internal" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.765885    2944 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-10-100-13-0.ec2.internalacmedev.com" is forbidden: User "system:node:ip-10-100-13-0.ec2.internal" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.766850    2944 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-10-100-13-0.ec2.internalacmedev.com\" is forbidden: node \"ip-10-100-13-0.ec2.internal\" is not allowed to modify node \"ip-10-100-13-0.ec2.internalacmedev.com\"" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.969984    2944 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.972246    2944 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-10-100-13-0.ec2.internalacmedev.com\" is forbidden: node \"ip-10-100-13-0.ec2.internal\" is not allowed to modify node \"ip-10-100-13-0.ec2.internalacmedev.com\"" node="ip-10-100-13-0.ec2.internalacmedev.com"
```

On the 1.25 nodes using `cloud-provider=aws` we can see the logs like:
```
Apr 12 15:14:31 ip-10-100-12-210 kubelet: I0412 15:14:31.176819    2906 server.go:993] "Cloud provider determined current node" nodeName="ip-10-100-12-210.ec2.internal"
```
https://github.com/kubernetes/kubernetes/blob/v1.26.2/cmd/kubelet/app/server.go#L989 which does not contain the `acmedev.com` appended to it.

The nodename returned in 1.25 aligns with with the templated private DNS name returned from the https://github.com/kubernetes-sigs/aws-iam-authenticator/tree/master that allows bootstrapping nodes. Since we are not using the aws cloud provider in 1.26 we might be getting back a different value for nodename which does not align.

Since the change to the `cloud-provider=external` I beieve we are returning the hostname that we would get from `hostname` or `uname -n`  e.g. `ip-10-100-13-0.ec2.internalacmedev.com` which does not align with what is returned from the EC2 api when getting the private DNS name for auth. Our node config in the aws-auth cm is standard:
```
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::1234567890:role/role-name"
      "username": "system:node:{{EC2PrivateDNSName}}"
```

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Fixes #1263 .

**Description of changes:**

Details available in #1263 .

This PR ensures that the name of the `Node` object matches the `PrivateDnsName` returned by `ec2.DescribeInstances`.

This `ec2.DescribeInstances` call was already being done by the in-tree cloud provider.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

Reproduce the issue by:
1. Create a 1.26 cluster: `eksctl create cluster --name 126 --version 1.26 --without-nodegroup`
2. Modify the created VPC's DHCP options set to use a custom `domain-name`:
```
domain-name: foo
domain-name-servers: AmazonProvidedDNS
```
3. Create a nodegroup: `eksctl create nodegroup --cluster 126`.
4. Nodegroup creation will fail.

Test the fix on the latest AMI release by:
1. `config.yaml`:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "126"
  region: us-west-2
  version: "1.26"
managedNodeGroups:
  - name: nodes
    ami: ami-022441ec63297a0c9
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    overrideBootstrapCommand: |
      #!/bin/bash
      INSTANCE_ID=$(imds /latest/meta-data/instance-id)
      PRIVATE_DNS_NAME=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].PrivateDnsName' --output text)
      /etc/eks/bootstrap.sh 126 --kubelet-extra-args "--node-labels=eks.amazonaws.com/nodegroup=nodes,eks.amazonaws.com/nodegroup-image=ami-022441ec63297a0c9 --hostname-override=$PRIVATE_DNS_NAME"
```
2. `eksctl create cluster --config-file config.yaml`
3. Nodes join the cluster as expected.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
This should not add any net-new `ec2.DescribeInstances` calls. Adding some breadcrumbs here to verify with the team tomorrow:
1. Kubelet calls `getNodeName` at startup: https://github.com/kubernetes/kubernetes/blob/29c8fb678c0cffffa5aebd021fab475b63bc1333/cmd/kubelet/app/server.go#L988-L1008
2. If a cloud provider is configured, `cloud.Instances().CurrentNodeName()` is called: https://github.com/kubernetes/kubernetes/blob/29c8fb678c0cffffa5aebd021fab475b63bc1333/cmd/kubelet/app/server.go#L1000
3. `CurrentNodeName` returns `selfAWSInstance.nodeName`: https://github.com/kubernetes/legacy-cloud-providers/blob/v0.25.9/aws/aws.go#L956
4. `selfAWSInstance` is created by `buildSelfAWSInstance()`, which does a `getInstanceByID`: https://github.com/kubernetes/legacy-cloud-providers/blob/v0.25.9/aws/aws.go#L2333-L2357
5. `getInstanceByID` calls `getInstancesByIDS`, which is where the magic happens: https://github.com/kubernetes/legacy-cloud-providers/blob/v0.25.9/aws/aws.go#L4844-L4869

**Review by camrakin — APPROVED** [review]

**Comment by cartermckinnon** [comment]
Putting this on hold until we've exhausted other options that don't require changes in every node AMI.

File: files/bootstrap.sh [hunk 1]
```diff
@@ -481,6 +481,13 @@ if vercmp "$KUBELET_VERSION" lt "1.26.0"; then
 else
   KUBELET_CLOUD_PROVIDER="external"
   echo "$(jq ".providerID=\"$(provider-id)\"" $KUBELET_CONFIG)" > $KUBELET_CONFIG
+  # When the external cloud provider is used, kubelet will use /etc/hostname as the name of the Node object.
+  # If the VPC has a custom `domain-name` in its DHCP options set, and the VPC has `enableDnsHostnames` set to `true`,
+  # then /etc/hostname is not the same as EC2's PrivateDnsName.
+  # The name of the Node object must be equal to EC2's PrivateDnsName for the aws-iam-authenticator to allow this kubelet to manage it.
+  INSTANCE_ID=$(imds /latest/meta-data/instance-id)
+  PRIVATE_DNS_NAME=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].PrivateDnsName' --output text)
```
Comment (bwagner5) [inline files/bootstrap.sh:489]: why not use IMDS instead?

```
imds latest/meta-data/local-hostname
i-00ccc01fc3fcd3e27.us-east-2.compute.internal
```
?

Comment (cartermckinnon) [reply files/bootstrap.sh:489]: `local-hostname` doesn't always match EC2's `PrivateDnsName`.

If:
1. A custom domain is configured on the VPC. (e.g. `foo`)
2. The VPC has `enableDnsHostnames` enabled

Then:
- `local-hostname` will be `$NAME.foo` (`NAME` is either resource-based or IP-based).
- `PrivateDnsName` will be `$NAME.$REGION.compute.internal`.

**Comment by cartermckinnon** [comment]
note: @saurav-agarwalla requested backoff/retries for the describeinstance call.

File: files/bootstrap.sh [hunk 2]
```diff
@@ -481,6 +481,13 @@ if vercmp "$KUBELET_VERSION" lt "1.26.0"; then
...
+  KUBELET_ARGS="$KUBELET_ARGS --hostname-override=$PRIVATE_DNS_NAME"
```
[the remark this answers is not in the document]
Comment (cartermckinnon) [reply files/bootstrap.sh]: The resource-based name is used in the `PrivateDnsName` (regardless of the custom domain config), so this covers that case as well.

**Review by mmerkes — APPROVED** [review]

**Comment by mikedizon** [comment]
Still having this issue. Is there anything in govcloud that would cause the same error?

**Comment by cartermckinnon** [comment]
@mikedizon this change hasn't been released in an official AMI build yet. Do you mean you've used a similar change yourself and it doesn't resolve the issue?

**Comment by mikedizon** [comment]
no, i thought it was already released

Michael Dizon

**Comment by cartermckinnon** [comment]
We have a build progressing through our pipeline, targeting early/mid next week for release 👍

**Comment by rmk135** [comment]
I faced this issue too. Thanks a lot for the fix! Waiting for the release.

**Comment by zinzh** [comment]
Any update on the release?

**Comment by rmk135** [comment]
Hi @cartermckinnon ,

Can you advice when we can expect a release with this fix?

**Comment by bryantbiggs** [comment]
> targeting early/mid next week for release

This has already been answered

**Comment by rmk135** [comment]
@bryantbiggs the week that was mentioned is already over

**Comment by mmerkes** [comment]
The release has been delayed and we weren't able to get it out last week. However, [we've committed to get a release out by 5/3/2023](https://github.com/awslabs/amazon-eks-ami/issues/1219#issuecomment-1526925860) at the latest, so if this doesn't roll out before then (still a possibility), it will go out then.

**Comment by rmk135** [comment]
@mmerkes copy that, thanks Matt!

**Comment by mmerkes** [comment]
`v20230501` is available in all regions now! Update to the latest EKS Optimized AMIs and this issue should be resolved.

**Comment by jitensingh12** [comment]
I'm facing same issue with EKS managed AMI : ami-0bc4534a93057f9fb... EKS: 1.27 (Latest)

**Comment by cartermckinnon** [comment]
@jitensingh12 Please open a new issue with the details of your environment and what error you're encountering.
