### PR TITLE
Use crictl to pull sandbox image

### LINKED ISSUE #1597: Sandbox container image being GC'd in 1.29
AMI: amazon-eks-node-1.29-v20240117

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to pull image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to pull and unpack image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to resolve reference "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": unexpected status from HEAD request to https://602401143452.dkr.ecr.eu-west-2.amazonaws.com/v2/eks/pause/manifests/3.5: 401 Unauthorized
```

1 day after upgrading EKS to 1.29

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Fixes #1597 on `containerd` 1.7.3+.

**Description of changes:**

The containerd CRI server will only report an image as "pinned" if it is *pulled* with the CRI server. The pinned label will not be applied if it is pulled using the bare `containerd` server with `ctr`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

On `containerd-1.7.11` with `sandbox_image = "registry.k8s.io/pause:3.9"`:
```
> sudo ctr --namespace k8s.io image pull registry.k8s.io/pause:3.9
> sudo crictl inspecti registry.k8s.io/pause:3.9 | grep pinned
    "pinned": false

> sudo crictl rmi --all
Deleted: registry.k8s.io/pause:3.9

> sudo crictl pull registry.k8s.io/pause:3.9
Image is up to date for sha256:e6f1816883972d4be47bd48879a08919b96afcd344132622e4d444987919323c
> sudo crictl inspecti registry.k8s.io/pause:3.9 | grep pinned
    "pinned": true
```

### CODE REVIEW

File: files/pull-sandbox-image.sh [hunk 1]
```diff
@@ -8,4 +8,9 @@ if [[ "$(sudo ctr --namespace k8s.io image ls | grep $sandbox_image)" != "" ]];
   exit 0
 fi
 
-/etc/eks/containerd/pull-image.sh "${sandbox_image}"
+ecr_password=$(aws ecr get-login-password)
```
Comment (dims) [inline files/pull-sandbox-image.sh:11]: if there is a problem with getting the password, will the timer (in the other PR) fail and then fail to re-fire again in the next time period?

**Comment by dims** [comment]
cc @henry118

File: files/pull-sandbox-image.sh (hunk 1 above)
Comment (cartermckinnon) [reply files/pull-sandbox-image.sh]: The timer will trigger the unit whether it failed or succeeded on previous runs, per my testing.

I copied over the `retry` logic we have in the other `pull-image.sh` script anyway.

File: files/pull-sandbox-image.sh [hunk 2]
```diff
@@ -8,4 +8,26 @@ if [[ "$(sudo ctr --namespace k8s.io image ls | grep $sandbox_image)" != "" ]];
   exit 0
 fi
 
-/etc/eks/containerd/pull-image.sh "${sandbox_image}"
```
Comment (tzneal) [inline files/pull-sandbox-image.sh:11]: Any reason not to modify the `pull-image.sh` script itself to use crictl instead of ctr?

Comment (cartermckinnon) [reply files/pull-sandbox-image.sh:11]: We use `ctr content fetch` in that script because it skips image unpacking (an important optimization for the image caching feature's disk usage).

File: files/pull-sandbox-image.sh [hunk 3]
```diff
@@ -8,4 +8,26 @@ if [[ "$(sudo ctr --namespace k8s.io image ls | grep $sandbox_image)" != "" ]];
...
+    sleep $sleep_sec
+  done
+}
+
+ecr_password=$(retry aws ecr get-login-password)
+if [[ -z ${ecr_password} ]]; then
+  echo >&2 "Unable to retrieve the ECR password."
+  exit 1
+fi
+sudo retry crictl pull "${sandbox_image}" --creds AWS:${ecr_password}
```
Comment (tzneal) [inline files/pull-sandbox-image.sh:33]: I just checked my node and crictl wasn't there. I think you need to install it as well.

Comment (cartermckinnon) [reply files/pull-sandbox-image.sh:33]: Right, missed in my commit 😓 . We mulled over adding `cri-tools` in the past because we aren't the maintainers of that package in AL. We don't have much of a choice now; the only other option would be manually labelling the image as pinned after we pull it with `ctr`.

**Review by henry118 — APPROVED** [review]
LGTM

**Review by tzneal — APPROVED** [review]
lgtm
