### PR TITLE
Decompress GZIP'd user data

### LINKED ISSUE #1734: nodeadm doesn't support userdata content-encoded with gzip
nodeadm fails with an error message about control characters in userdata when the userdata has content-encoded with gzip, while cloud-init uncompresses the userdata just fine.  Disabling gzip of userdata allowed nodeadm to work as expected.

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Fixes #1734 

**Description of changes:**

Adds support for GZIP-compressed user data.

The following scenarios are supported:
1. User data that consists of a `NodeConfig` that is compressed with GZIP.
2. User data that is a multi-part MIME document that is compressed with GZIP.
3. User data that is a multi-part MIME document containing parts that are individually GZIP'd (and have the `Content-Encoding: gzip` header).
4. A combination of 2 and 3.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ndbaker1 — COMMENTED** [review]
the change LGTM. doesn't seem like we are going to adopt decompressing individual parts, so can we do a doc update before merging?

**Comment by cartermckinnon** [comment]
>  doesn't seem like we are going to adopt decompressing individual parts

@ndbaker1 latest rev adds support for this, PTAL.

File: nodeadm/internal/configprovider/userdata_test.go
Comment (cartermckinnon) [inline nodeadm/internal/configprovider/userdata_test.go:1]: I rewrote the unit tests for this class; they're more verbose but I think being explicit about the input is more clear and lets us more easily add test cases in the future.

File: nodeadm/internal/configprovider/userdata.go [hunk 1]
```diff
@@ -17,22 +18,41 @@ import (
...
+
+type imdsUserDataProvider struct{}
+
+func (p *imdsUserDataProvider) GetUserData() ([]byte, error) {
+	return imds.GetUserData()
+}
+
+type userDataConfigProvider struct {
+	userDataProvider userDataProvider
+}
```
Comment (mmerkes) [inline nodeadm/internal/configprovider/userdata.go:39]: Why do you need this wrapper?

File: nodeadm/internal/configprovider/userdata.go [hunk 2]
```diff
@@ -17,22 +18,41 @@ import (
...
 
 func NewUserDataConfigProvider() ConfigProvider {
-	return &userDataConfigProvider{}
+	return &userDataConfigProvider{
+		userDataProvider: &imdsUserDataProvider{},
+	}
 }
 
 func (ics *userDataConfigProvider) Provide() (*internalapi.NodeConfig, error) {
```
Comment (mmerkes) [inline nodeadm/internal/configprovider/userdata.go:47]: Why is `ics` the name for `userDataConfigProvider`?

File: nodeadm/internal/configprovider/userdata.go [hunk 3]
```diff
@@ -85,6 +105,13 @@ func parseMultipart(userDataReader *multipart.Reader) (*internalapi.NodeConfig,
 				if err != nil {
 					return nil, err
 				}
+				if part.Header.Get(contentEncodingHeader) == "gzip" {
+					decompressedNodeConfigPart, err := decompressIfGZIP(nodeConfigPart)
+					if err != nil {
+						return nil, err
+					}
+					nodeConfigPart = decompressedNodeConfigPart
+				}
```
Comment (mmerkes) [inline nodeadm/internal/configprovider/userdata.go:114]: Why do you need to make a check that it's `gzip` and then gracefully handle it not being `gzip`?

File: nodeadm/internal/configprovider/userdata_test.go
Comment (mmerkes) [reply nodeadm/internal/configprovider/userdata_test.go:1]: Did you do any integration testing here? Or is that covered by the existing integration tests?

File: nodeadm/internal/configprovider/userdata.go (hunk 3 above)
Comment (ndbaker1) [reply nodeadm/internal/configprovider/userdata.go:114]: wouldn't just calling `decompressIfGZIP` in all cases work better since its fallible in constant time and safe either way?

To not hit this branch you'd have to set the nodeConfig mediaType but forget to add the gzip encoding header, which im sure would only happen on accident. maybe handling it explicitly is more "proper", but not sure if its necessary

File: nodeadm/internal/configprovider/userdata.go (hunk 2 above)
Comment (ndbaker1) [reply nodeadm/internal/configprovider/userdata.go:47]: i think it's an artifact from when it was something like `imdsConfigProvider`? 🤣   
maybe we could just generally name the config provider references `cp`

File: nodeadm/internal/configprovider/userdata_test.go
Comment (ndbaker1) [reply nodeadm/internal/configprovider/userdata_test.go:1]: i like the change, thanks for skipping over the junk to setup mime documents and testing the actual provider interface

File: nodeadm/internal/configprovider/userdata.go [hunk 4]
```diff
@@ -17,22 +18,41 @@ import (
...
+	contentEncodingHeader      = "Content-Encoding"
 	mimeBoundaryParam          = "boundary"
 	multipartContentTypePrefix = "multipart/"
 	nodeConfigMediaType        = "application/" + api.GroupName
 )
 
-type userDataConfigProvider struct{}
+type userDataProvider interface {
+	GetUserData() ([]byte, error)
+}
```
Comment (ndbaker1) [inline nodeadm/internal/configprovider/userdata.go:29]: nice way to make testing the provider interface easier 👍

File: nodeadm/internal/configprovider/userdata.go (hunk 2 above)
Comment (cartermckinnon) [reply nodeadm/internal/configprovider/userdata.go:47]: tbh i like just calling it `this` but that's a Java-ism that gophers detest

File: nodeadm/internal/configprovider/userdata.go (hunk 1 above)
Comment (cartermckinnon) [reply nodeadm/internal/configprovider/userdata.go:39]: This is for testing, it allows us to mock out the IMDS calls

File: nodeadm/internal/configprovider/userdata.go (hunk 3 above)
Comment (cartermckinnon) [reply nodeadm/internal/configprovider/userdata.go:114]: MIME semantics dictate that if the section is GZIP'd, this header needs to be there. If a user (or library) is creating MIME documents that use GZIP but omit this header, that should fail because it's not conformant to the spec.

Generally, folks are only using GZIP compression via a library which should implement this properly -- folks aren't hand-writing and hand-compressing their MIME docs.

File: nodeadm/internal/configprovider/userdata.go (hunk 2 above)
Comment (mmerkes) [reply nodeadm/internal/configprovider/userdata.go:47]: Haha. Let's change it to something that makes sense :P

**Comment by cartermckinnon** [comment]
/ci
+workflow:os_distros al2023

**Comment by cartermckinnon** [comment]
One flake:

> [Fail] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] [It] updates the published spec when one version gets renamed [Conformance] 

Re-running for sanity

File: nodeadm/internal/configprovider/userdata.go (hunk 3 above)
Comment (cartermckinnon) [reply nodeadm/internal/configprovider/userdata.go]: Turns out cloudinit doesn't care what the spec says, and just tries to base64-decode and gzip-decompress pretty much anything it handles at any scope. It's more important for us to match the cloudinit behavior than to follow the spec, for better or worse. Updated in latest rev

**Comment by cartermckinnon** [comment]
/ci
+workflow:os_distros al2023

File: nodeadm/internal/configprovider/userdata.go [hunk 5]
```diff
@@ -85,6 +109,14 @@ func parseMultipart(userDataReader *multipart.Reader) (*internalapi.NodeConfig,
 				if err != nil {
 					return nil, err
 				}
+				nodeConfigPart, err = decodeIfBase64(nodeConfigPart)
+				if err != nil {
+					return nil, err
+				}
+				nodeConfigPart, err = decompressIfGZIP(nodeConfigPart)
+				if err != nil {
+					return nil, err
```
Comment (ndbaker1) [inline nodeadm/internal/configprovider/userdata.go:118]: nit: theres a custom error message around the calls above but not here :(

File: nodeadm/internal/configprovider/userdata.go [hunk 6]
```diff
@@ -102,6 +134,39 @@ func parseMultipart(userDataReader *multipart.Reader) (*internalapi.NodeConfig,
...
+	}
+}
+
+func decodeIfBase64(data []byte) ([]byte, error) {
+	e := base64.StdEncoding
+	maxDecodedLen := e.DecodedLen(len(data))
+	decodedData := make([]byte, maxDecodedLen)
+	decodedLen, err := e.Decode(decodedData, data)
+	if err != nil {
+		return data, nil
```
Comment (ndbaker1) [inline nodeadm/internal/configprovider/userdata.go:147]: so none of the possible errors here end up mattering?

File: nodeadm/internal/configprovider/userdata.go (hunk 5 above)
Comment (ndbaker1) [reply nodeadm/internal/configprovider/userdata.go:118]: actually the more i think on this, should we be more tolerant and `break` on these errors so that we can try the remaining parts?

File: nodeadm/internal/configprovider/userdata.go (hunk 6 above)
Comment (ndbaker1) [reply nodeadm/internal/configprovider/userdata.go:147]: oh i guess it can only return [`CorruptInputError`](https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/encoding/base64/base64.go;l=301-305) 🤔

**Review by ndbaker1 — APPROVED** [review]
lgtm as-is, one nit comment
