### PR TITLE
fix(nodeadm): improve error handling for install-nodeadm.sh

### LINKED ISSUE #2404: bug(nodeadm): failed at `install-nodeadm.sh` due to duplicate image ids passed as `nerdctl rmi` argument
**What happened**:

By current design, the `nerdctl rmi` did not check for duplicated input of image ids

https://github.com/awslabs/amazon-eks-ami/blob/8f395aaa776ff7bbfe52188a6164b1a10875e36d/templates/al2023/provisioners/install-nodeadm.sh#L25-L29

which would cause error as follow

```log
...
==> amazon-ebs: Untagged: public.ecr.aws/eks-distro-build-tooling/golang:1.24@sha256:33c19e0f650564a7ade227088ff27f0d0abeede1ff3d1a01ed3f83eebfc3768d
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: FATA[0000] 1 errors:
==> amazon-ebs: filters: parse error: [name==66c8619930b9 >|
==> amazon-ebs: |< 66c8619930b9]: unexpected input:
==> amazon-ebs: : invalid argument: invalid argument
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
...
```

**What you expected to happen**:

Should have no error returns

**How to reproduce it (as minimally and precisely as possible)**:

```
make
```

**Environment**:
 
- AWS Region: `any`
- Instance Type(s): `any`
- Cluster Kubernetes version: `any`
- Node Kubernetes version: `any`
- AMI Version: `any`

### PR DESCRIPTION
**Pull request by guessi**
**Issue #, if available:**

Fix #2404

**Description of changes:**

* Leverage `nerdctl` bulit-in mechanism to cleanup image but not handle by hand.
* Basic validation for the script inputs before actual run.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

## Before

```
...
==> amazon-ebs: Untagged: public.ecr.aws/eks-distro-build-tooling/golang:1.24@sha256:33c19e0f650564a7ade227088ff27f0d0abeede1ff3d1a01ed3f83eebfc3768d
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: Deleted: sha256:...
==> amazon-ebs: FATA[0000] 1 errors:
==> amazon-ebs: filters: parse error: [name==66c8619930b9 >|
==> amazon-ebs: |< 66c8619930b9]: unexpected input:
==> amazon-ebs: : invalid argument: invalid argument
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
...
```

## After

```
==> amazon-ebs: Provisioning with shell script: /Users/kuole/personal/github/forks/amazon-eks-ami/templates/al2023/provisioners/install-nodeadm.sh
...
==> amazon-ebs: GOOS= go build -o /workdir/_bin/ ./cmd/...
==> amazon-ebs: Untagged: public.ecr.aws/eks-distro-build-tooling/golang:1.24@sha256:33c19e0f650564a7ade227088ff27f0d0abeede1ff3d1a01ed3f83eebfc3768d
==> amazon-ebs: Deleted: sha256:8950f7ce66298fd409c4af64b1b7dbb8e562b2d8cc53b3117596e30ef1a7d33c
==> amazon-ebs: Deleted: sha256:ff3bff54c5663fc0e68e127d4fc7853a1cbf651569374b87cbc2f62ce62a2db4
==> amazon-ebs: Deleted: sha256:109e6b9b5be8c4946209bffd3582375399e7fdfc5bc1c8b18c367430b4674fc6
==> amazon-ebs: Deleted: sha256:de3b158b9897435495abb07d46b3518b229f09d8b8a5f330af8c7c55bc321aa6
==> amazon-ebs: Deleted: sha256:2dc2cee773e6f0df84ebad933a3f18aca874da4bc2bdccc327debab149a4e3d2
==> amazon-ebs: Deleted Images:
==> amazon-ebs: Untagged: sha256:1f3a5962c3a7266f80f07341e1265e6f5981a253246708acae021319f4e2dbb7
==> amazon-ebs: deleted: sha256:8950f7ce66298fd409c4af64b1b7dbb8e562b2d8cc53b3117596e30ef1a7d33c
==> amazon-ebs: deleted: sha256:ff3bff54c5663fc0e68e127d4fc7853a1cbf651569374b87cbc2f62ce62a2db4
==> amazon-ebs: deleted: sha256:109e6b9b5be8c4946209bffd3582375399e7fdfc5bc1c8b18c367430b4674fc6
==> amazon-ebs: deleted: sha256:de3b158b9897435495abb07d46b3518b229f09d8b8a5f330af8c7c55bc321aa6
==> amazon-ebs: deleted: sha256:2dc2cee773e6f0df84ebad933a3f18aca874da4bc2bdccc327debab149a4e3d2
==> amazon-ebs:
==> amazon-ebs: Created symlink /etc/systemd/system/multi-user.target.wants/nodeadm-boot-hook.service → /etc/systemd/system/nodeadm-boot-hook.service.
==> amazon-ebs: Created symlink /etc/systemd/system/multi-user.target.wants/nodeadm-config.service → /etc/systemd/system/nodeadm-config.service.
==> amazon-ebs: Created symlink /etc/systemd/system/multi-user.target.wants/nodeadm-run.service → /etc/systemd/system/nodeadm-run.service.
==> amazon-ebs: Provisioning with shell script: /Users/kuole/personal/github/forks/amazon-eks-ami/templates/al2023/provisioners/cache-pause-container.sh
...
```

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

### CODE REVIEW

File: templates/al2023/provisioners/install-nodeadm.sh [hunk 1]
```diff
@@ -25,8 +41,10 @@ sudo nerdctl run \
 # cleanup build image and snapshots
 sudo nerdctl rmi \
   --force \
-  $BUILD_IMAGE \
-  "$(sudo nerdctl images -a | grep none | awk '{ print $3 }')"
+  $BUILD_IMAGE
+
+# Remove all unused images
+sudo nerdctl image prune --force
```
Comment (ndbaker1) [inline templates/al2023/provisioners/install-nodeadm.sh]: nit on the comment,
```suggestion
# cleanup dangling images
sudo nerdctl image prune --force
```
thanks for swapping this in, its a lot cleaner 😅

Comment (guessi) [reply templates/al2023/provisioners/install-nodeadm.sh]: Will fix, give me 5 minutes... On my way to my laptop 😆

Comment (guessi) [reply templates/al2023/provisioners/install-nodeadm.sh]: BTW, it's actually copy from `nerdctl -h`
* https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/image/image_prune.go#L33

Comment (guessi) [reply templates/al2023/provisioners/install-nodeadm.sh]: Updated!
